<a href="https://colab.research.google.com/github/supersahib/Pytorch-Learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

### Resource - https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors created using `torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
print(TENSOR[0])
print(TENSOR[0].shape)

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])
torch.Size([3, 3])


### Random Tensors


Random tesnors are important because the way neural networks learn is that they start with random tensors full of random #'s and adjust those random #'s to better represent the data

In [ ]:
#rand tensor of size (3,4)
randomTensor = torch.rand(3,4)
randomTensor

tensor([[0.3651, 0.3126, 0.4024, 0.5770],
        [0.7234, 0.7436, 0.2961, 0.4534],
        [0.5260, 0.0095, 0.7697, 0.8649]])

In [ ]:
randomTensor.ndim

2

In [ ]:
randomTensor.shape

torch.Size([3, 4])

In [ ]:
# create rand tensor with similar shape to an image tensor

#height, width, colour channels
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# create tensor of all zeros
zeros = torch.zeros(size=[3,4])
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*randomTensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
mask = torch.ones([3,4])
mask[:, 1] = 0
mask

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
randomTensor*mask

tensor([[0.3651, 0.0000, 0.4024, 0.5770],
        [0.7234, 0.0000, 0.2961, 0.4534],
        [0.5260, 0.0000, 0.7697, 0.8649]])

In [ ]:
ones = torch.ones([3,4])
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
#use torch.range()
a = torch.arange(0,10)
b = torch.arange(start=1, end=1000, step=55)
a, b

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([  1,  56, 111, 166, 221, 276, 331, 386, 441, 496, 551, 606, 661, 716,
         771, 826, 881, 936, 991]))

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(a)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor dataypes is one of the 3 big errors you will run into with Pytorch & deep learning:

1: Tensors not right datatype
2: Tensors not right shape
3: Tensors not on the right device

Precision in computing:
https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor
                               device=None, #what device is your tensor on default is  'cpu'
                               requires_grad=False) #whether or not to track gradients with this tensors operations

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor
                               device='cuda',
                               requires_grad=False)
float_32_tensor

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
x = float_16_tensor * float_32_tensor
x.dtype

torch.float32

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
#create tensor

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
a = tensor * 2
b = torch.mul(tensor, 10)
a,b

(tensor([2, 4, 6]), tensor([10, 20, 30]))

In [ ]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

### Matrix multiplication
two main ways of performing mult in neural networks & deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

https://www.mathsisfun.com/algebra/matrix-multiplying.html


There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work

2. The resulting matrix has the shape of the outer dimensions
* `(2,3) @ (3,2)` will become `(2,2)`


In [ ]:
#element wise mult

print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#matrix multiplication

torch.matmul(tensor, tensor)


tensor(14)

In [ ]:
#matrix multiplication by hand
tensor[0]*tensor[0] + tensor[1]*tensor[1] + tensor[2]*tensor[2]

tensor(14)

In [ ]:
for i in range(len(tensor)):
    print(tensor[i])

tensor(1)
tensor(2)
tensor(3)


To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
tensor_A.shape, tensor_B.shape
#torch.matmul(tensor_A, tensor_B) will not work --

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B.T #transpose

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
transpose_mul = torch.matmul(tensor_A, tensor_B.T)
transpose_mul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
transpose_mul.shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
#max
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [ ]:
#mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#mean
torch.mean(x.type(torch.float)), torch.mean(x, dtype=torch.float), x.type(torch.float).mean()

(tensor(45.), tensor(45.), tensor(45.))

In [ ]:
#Sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
#find the position in the tensor that has the minimum value with argmin() --> returns index position of target tensor where the minimumm value occurs
x.argmin()

tensor(0)

In [ ]:
#find position of max value

x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).. Basically concatentation