<a href="https://colab.research.google.com/github/supersahib/Pytorch-Learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

### Resource - https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors created using `torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX

MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
print(TENSOR[0])
print(TENSOR[0].shape)

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])
torch.Size([3, 3])


### Random Tensors


Random tesnors are important because the way neural networks learn is that they start with random tensors full of random #'s and adjust those random #'s to better represent the data

In [17]:
#rand tensor of size (3,4)
randomTensor = torch.rand(3,4)
randomTensor

tensor([[0.8560, 0.1361, 0.5183, 0.4405],
        [0.3279, 0.3168, 0.0709, 0.9857],
        [0.6077, 0.0603, 0.1487, 0.3825]])

In [18]:
randomTensor.ndim

2

In [19]:
randomTensor.shape

torch.Size([3, 4])

In [20]:
# create rand tensor with similar shape to an image tensor

#height, width, colour channels
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [21]:
# create tensor of all zeros
zeros = torch.zeros(size=[3,4])
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*randomTensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
mask = torch.ones([3,4])
mask[:, 1] = 0
mask

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
randomTensor*mask

tensor([[0.8560, 0.0000, 0.5183, 0.4405],
        [0.3279, 0.0000, 0.0709, 0.9857],
        [0.6077, 0.0000, 0.1487, 0.3825]])

In [25]:
ones = torch.ones([3,4])
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [26]:
#use torch.range()
a = torch.arange(0,10)
b = torch.arange(start=1, end=1000, step=55)
a, b

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([  1,  56, 111, 166, 221, 276, 331, 386, 441, 496, 551, 606, 661, 716,
         771, 826, 881, 936, 991]))

In [27]:
#creating tensors like
ten_zeros = torch.zeros_like(a)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor dataypes is one of the 3 big errors you will run into with Pytorch & deep learning:

1: Tensors not right datatype
2: Tensors not right shape
3: Tensors not on the right device

Precision in computing:
https://en.wikipedia.org/wiki/Precision_(computer_science)

In [28]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor
                               device=None, #what device is your tensor on default is  'cpu'
                               requires_grad=False) #whether or not to track gradients with this tensors operations

In [32]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor
                               #device='cuda',
                               requires_grad=False)
float_32_tensor

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [53]:
x = float_16_tensor * float_32_tensor
x.dtype

torch.float32

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [54]:
#create tensor

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [55]:
tensor - 10

tensor([-9, -8, -7])

In [56]:
a = tensor * 2
b = torch.mul(tensor, 10)
a,b

(tensor([2, 4, 6]), tensor([10, 20, 30]))

In [57]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

### Matrix multiplication
two main ways of performing mult in neural networks & deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

https://www.mathsisfun.com/algebra/matrix-multiplying.html


There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work

2. The resulting matrix has the shape of the outer dimensions
* `(2,3) @ (3,2)` will become `(2,2)`


In [58]:
#element wise mult

print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [59]:
#matrix multiplication

torch.matmul(tensor, tensor)


tensor(14)

In [60]:
#matrix multiplication by hand
tensor[0]*tensor[0] + tensor[1]*tensor[1] + tensor[2]*tensor[2]

tensor(14)

In [61]:
for i in range(len(tensor)):
    print(tensor[i])

tensor(1)
tensor(2)
tensor(3)


To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [62]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
tensor_A.shape, tensor_B.shape
#torch.matmul(tensor_A, tensor_B) will not work --

(torch.Size([3, 2]), torch.Size([3, 2]))

In [63]:
tensor_B.T #transpose

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [64]:
transpose_mul = torch.matmul(tensor_A, tensor_B.T)
transpose_mul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [65]:
transpose_mul.shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [66]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [67]:
# min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [68]:
#max
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [69]:
#mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [70]:
#mean
torch.mean(x.type(torch.float)), torch.mean(x, dtype=torch.float), x.type(torch.float).mean()

(tensor(45.), tensor(45.), tensor(45.))

In [71]:
#Sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [72]:
#find the position in the tensor that has the minimum value with argmin() --> returns index position of target tensor where the minimumm value occurs
x.argmin()

tensor(0)

In [73]:
#find position of max value

x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).. Basically concatentation
* Squeeze - removes dimensions of size 1 from a tensor
* Unsqueeze - Returns a new tensor with a dimension of size one inserted at the specified position.
* Permute - return view of the input with dimensions permuted/swapped in some way

In [74]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [75]:
# extra dimension
x_extra_dim = x.reshape(3,3)
x_extra_dim

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [76]:
# lets try with 2x2 9 ele
x_reshape_2x2 = x.reshape(2,2)

RuntimeError: shape '[2, 2]' is invalid for input of size 9

In [77]:
x_reshape_9x1 = x.reshape(9,1)
x_reshape_9x1

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [78]:
x_reshape_9x1.reshape(-1)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [79]:
# change the view (view shares memory of original tensor)
z = x.view(1,9)
x, z, x.shape, z.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([9]),
 torch.Size([1, 9]))

In [80]:
# changing view will change the underlying original tensor
z[0][0] = 10
x

tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [81]:
# stack tensors on top - All tensors need to be of the same size.
#torch.stack

In [82]:
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [95]:
#torch.squeeze
x = torch.zeros(2, 1, 2, 1, 2)
print(f'tensor before squeeze:\n {x}')
print(f'tensor shape before squeeze: {x.shape}')

y = torch.squeeze(x)
print(f'\ntensor after torch.squeeze(x):\n {y}')
print(f'tensor shape after torch.squeeze(x): {y.shape}')

y = torch.squeeze(x, 0)
print(f'\ntensor after torch.squeeze(x,0):\n {y}')
print(f'tensor shape after torch.squeeze(x,0): {y.shape}')

y = torch.squeeze(x, 1)
print(f'\ntensor after torch.squeeze(x,1):\n {y}')
print(f'tensor shape after torch.squeeze(x,1): {y.shape}')

y = torch.squeeze(x, (1, 2, 3))
print(f'\ntensor after torch.squeeze(x,(1,2,3)): {y}')
print(f'tensor shape after torch.squeeze(x,(1,2,3)): {y.shape}')

tensor before squeeze:
 tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
tensor shape before squeeze: torch.Size([2, 1, 2, 1, 2])

tensor after torch.squeeze(x):
 tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor shape after torch.squeeze(x): torch.Size([2, 2, 2])

tensor after torch.squeeze(x,0):
 tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
tensor shape after torch.squeeze(x,0): torch.Size([2, 1, 2, 1, 2])

tensor after torch.squeeze(x,1):
 tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])
tensor shape after torch.squeeze(x,1): torch.Size([2, 2, 1, 2])

tensor after torch.squeeze(x,(1,2,3)): tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor shape after torch.squeeze(x,(1,2,3)): torch.Size([2, 2, 2])


In [102]:
#torch.unsqueeze

x = torch.arange(1., 10.)
print(f"Previous target: {x}")
print(f"Previous shape: {x.shape}")

#add an extra dim with unsqueeze
x_unsqueezed = x.unsqueeze(dim=0)
print(f"\nAfter unsqueeze(dim=0): {x_unsqueezed}")
print(f"After unsqueeze(dim=0) shape: {x_unsqueezed.shape}")

x_unsqueezed_dim_1 = x.unsqueeze(dim=1)
print(f"\nAfter unsqueeze(dim=1): {x_unsqueezed_dim_1}")
print(f"After unsqueeze(dim=1) shape: {x_unsqueezed_dim_1.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

After unsqueeze(dim=0): tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
After unsqueeze(dim=0) shape: torch.Size([1, 9])

After unsqueeze(dim=1): tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
After unsqueeze(dim=1) shape: torch.Size([9, 1])


In [4]:
# torch.permute - rearranges the dimensions of a target tensor in specified order

x_original = torch.rand(size=(224,224,3)) #[height,width,colour_channels]

# permute the original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute((2,0,1,)) #shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [9]:
#changing val
print(f"before first ele of x_original: {x_original[0,0,0]}")
x_original[0,0,0] = 5
print(f"after change, here is x_permuted first ele {x_permuted[0,0,0]}")
x_permuted[0,0,0]

#they share memory

before first ele of x_original: 0.6603419780731201
after change, here is x_permuted first ele 5.0


tensor(5.)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [11]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))